# Generated by Django 5.1.4 on 2025-05-15 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('land_type', models.CharField(choices=[('agriculture', 'Agriculture'), ('residential', 'Residential'), ('industrial', 'Industrial'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='adhar_card',
            field=models.ImageField(blank=True, null=True, upload_to='documents/adhar/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='documents/pan/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.CreateModel(
            name='LandProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_ekhata_registered', models.BooleanField(default=False)),
                ('land_use_type', models.CharField(choices=[('agriculture', 'Agriculture'), ('residential', 'Residential'), ('other', 'Other')], max_length=50)),
                ('expected_price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('is_sold', models.BooleanField(default=False)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('last_tax_paid_receipt', models.FileField(blank=True, null=True, upload_to='tax_receipts/')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.landrecord')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_min', models.PositiveIntegerField()),
                ('budget_max', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preferred_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.landrecord')),
            ],
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='documents/cases/')),
                ('remarks', models.TextField(blank=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.landproperty')),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('ownership_order', models.PositiveIntegerField()),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.landproperty')),
                ('new_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='landproperty',
            name='sellers',
            field=models.ManyToManyField(to='accounts.sellerprofile'),
        ),
    ]
