# Generated by Django 5.1.4 on 2025-05-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_landimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landproperty',
            name='land_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_by_record', to='accounts.landrecord'),
        ),
        migrations.AlterField(
            model_name='landproperty',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_by_place', to='accounts.landrecord'),
        ),
    ]
